driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: freebsd-11
  - name: fedora-27
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: openjdk-6
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - ubuntu-14.04
    run_list:
      - recipe[test_java::openjdk6]
  - name: openjdk-7
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - freebsd-11
      - opensuse-leap-42
      - ubuntu-14.04
      - ubuntu-16.04
    run_list:
      - recipe[test_java::openjdk7]
  - name: openjdk-8
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-9
      - fedora-27
      - freebsd-11
      - opensuse-leap-42
      - ubuntu-14.04
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test_java::openjdk8]
  - name: oracle-8
    run_list:
      - recipe[test_java::oracle8]
  - name: oracle-direct
    run_list:
      - recipe[test_java::oracle_direct]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
  - name: openjdk-direct
    run_list:
      - recipe[test_java::openjdk_direct]
  - name: oracle-rpm-8
    includes:
      - centos-6
      - centos-7
      - fedora-27
    run_list:
      - recipe[test_java::oracle_rpm8]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
