sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  #- INSTANCE=openjdk-6-amazon-linux
  - INSTANCE=openjdk-6-centos-6
  - INSTANCE=openjdk-6-centos-7
  - INSTANCE=openjdk-6-ubuntu-1404
  #- INSTANCE=openjdk-7-amazon-linux
  - INSTANCE=openjdk-7-centos-6
  - INSTANCE=openjdk-7-centos-7
  - INSTANCE=openjdk-7-debian-8
  - INSTANCE=openjdk-7-ubuntu-1404
  - INSTANCE=openjdk-7-ubuntu-1604
  # - INSTANCE=openjdk-8-amazon-linux
  - INSTANCE=openjdk-8-centos-6
  - INSTANCE=openjdk-8-centos-7
  - INSTANCE=openjdk-8-debian-9
  - INSTANCE=openjdk-8-fedora-27
  # - INSTANCE=openjdk-8-ubuntu-1404 # error querying keystore for existing certificate
  - INSTANCE=openjdk-8-ubuntu-1604
  - INSTANCE=openjdk-8-ubuntu-1804
  - INSTANCE=oracle-8-centos-6
  - INSTANCE=oracle-8-centos-7
  - INSTANCE=oracle-8-debian-8
  - INSTANCE=oracle-8-debian-9
  - INSTANCE=oracle-8-ubuntu-1404
  - INSTANCE=oracle-8-ubuntu-1604
  - INSTANCE=oracle-8-ubuntu-1804

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - delivery local all
      env: UNIT_AND_LINT=1
